### ISSUE TITLE
Add timestamp from EEL file in `step` command output

### ISSUE THREAD

**Issue by vinsworldcom** [adjacentlink/emane-node-director#1]
Awesome tool!  Finally the ability to play, pause, fast-forward, rewind a scenario.

Is it possible to add the timestep from the EEL file in the output of the `step` command?  It would make it easier to track as human reading the output, where in the EEL file we're at.

Cheers.

**Comment by eschreiber-alink** [comment]
Added to develop branch.

**Comment by eschreiber-alink** [comment]
Released to v0.2.2.

**Comment by vinsworldcom** [comment]
@eschreiber-alink just verified in testing - works great!  Thank you.
